#
# MANAGED BY ANSIBLE
#

# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

USE="X policykit gnome gtk alsa video_cards_radeonsi -gpm -gnome-online-accounts -qt5 -kde -ipv6 -video_cards_r600 -video_cards_r300"
#-video_cards_radeon -video_cards_r600 -video_cards_r300" 
VIDEO_CARDS="amdgpu radeon radeonsi" 
ACCEPT_LICENSE="*"
ABI_X86="32 64"

GENTOO_MIRRORS="https://mirror.umd.edu/gentoo/ \
    http://mirror.umd.edu/gentoo/ \
    rsync://mirror.umd.edu/gentoo/"
