# Ensure necessary services are enabled and started
---
- name: Enable libvirtd socket
  become: yes
  ansible.builtin.service:
    name: "{{ systemd_unit }}"
    enabled: true
    state: started
  loop:
    - 'libvirtd.socket'
    - 'libvirtd.service'
  loop_control:
    loop_var: systemd_unit
