#!/bin/bash
#
# Aliases I expect to be set in my environment

#
# MANAGED BY ANSIBLE
#

# Require interaction from commands which can delete files
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# Some convenient shortcuts for ls
alias ls='ls --color=auto'
alias ll='ls -l'
alias la='ls -A'

# Shortcuts for grep 
alias grep='grep --color=auto'

# Check password easily
alias pass='ansible-vault view /etc/ansible/pass.yaml'

# Open games library easily
alias library='/files/python/game-library-tui/library.py'

# Open gallery easily
alias gallery='/files/python/gallery-filter-tui/gallery.py'

# Open trivia game easily
alias trivia='/files/python/rogue-trivia-tui/trivia.py'
