---
- name: Reload sshd
  become: true
  ansible.builtin.service:
    name: sshd
    state: reloaded

- name: Restart usbguard
  become: true
  ansible.builtin.service:
    name: usbguard
    state: restarted

- name: Secure active mounts
  become: true
  ansible.posix.mount:
    path: "{{ lookup('vars', mount + '_mountpoint') }}"
    src: "{{ lookup('vars', mount + '_volume') }}"
    fstype: "{{ lookup('vars', mount + '_type') }}"
    opts: "{{ lookup('vars', mount + '_opts') }}"
    state: remounted
  loop:
    - boot
    - dev
    - devshm
    - proc
    - home
    - tmp
    - var
    - log
    - audit
  loop_control:
    loop_var: mount

- name: Reload sysctl
  become: true
  ansible.builtin.shell: sysctl --system
