---
- name: Reload sshd
  become: true
  ansible.builtin.service:
    name: sshd
    state: reloaded

- name: Restart usbguard
  become: true
  ansible.builtin.service:
    name: usbguard
    state: restarted
