# Ensure that common mountpoints are mounted securely
---
- name: Ensure users that need to be in the proc group are added
  become: true
  ansible.builtin.user:
    user: "{{ proc_user }}"
    groups: proc
    append: true
  loop:
    - polkitd
    - "{{ user }}"
  loop_control:
    loop_var: proc_user

- name: Apply secure mount settings in fstab
  become: true
  ansible.posix.mount:
    path: "{{ lookup('vars', mount + '_mountpoint') }}"
    src: "{{ lookup('vars', mount + '_volume') }}"
    fstype: "{{ lookup('vars', mount + '_type') }}"
    opts: "{{ lookup('vars', mount + '_opts') }}"
    state: present
  loop:
    - boot
    - dev
    - devshm
    - proc
    - home
    - tmp
    - var
    - log
    - audit
  loop_control:
    loop_var: mount
  notify: Secure active mounts
