# Ensure lightdm is configured to use chosen greeter
---
- name: Ensure that lightdm is using custom greeter
  become: true
  community.general.ini_file:
    path: /etc/lightdm/lightdm.conf
    section: 'Seat:*'
    option: greeter-session
    value: lightdm-slick-greeter
    create: true
    owner: root
    group: root
    mode: '0600'
