# For configuring my user account after an install
---
- name: Create Required Directories
  ansible.builtin.file:
    path: "{{ user_info.home }}/{{ user_req_directory }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user_info.group }}"
    mode: "0700"
  loop: "{{ user_req_directories }}"
  loop_control:
    loop_var: user_req_directory

- name: Deploy user dotfiles
  ansible.builtin.copy:
    src: "users/{{ dotfile.src }}"
    dest: "{{ user_info.home }}/{{ dotfile.dest }}"
    owner: "{{ user }}"
    group: "{{ user_info.group }}"
    mode: '0400'
  loop: "{{ user_dotfiles }}"
  loop_control:
    loop_var: dotfile

- name: Create application cache symlinks
  ansible.builtin.file:
    src: "{{ appcache }}/{{ symlink.src }}"
    dest: "{{ user_info.home }}/{{ symlink.dest }}"
    state: link
    owner: "{{ user }}"
    group: "{{ user_info.group }}"
  loop: "{{ user_symlinks }}"
  loop_control:
    loop_var: symlink

- name: Configure Automount of gocryptfs for user
  become: true
  template:
    src: templates/pam_mount.conf.xml
    dest: /etc/security/pam_mount.conf.xml
    owner: "{{ user }}"
    group: "{{ user_info.group }}"
    mode: '0644'

- name: Configure Automount during login
  become: true
  template:
    src: files/pam/lightdm
    dest: /etc/pam.d/lightdm
    owner: root
    group: root
    mode: '0644'
