# Install flatpak applications for the systen
---
- name: Add the Flathub repository
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Install system Flatpak apps
  become: true
  community.general.flatpak:
    name: "{{ flatpak }}"
    state: present
    method: system
  loop: "{{ flatpaks_to_install }}"
  loop_control:
    loop_var: flatpak
