# Install custom list of packages on top of initial install
---
- name: Verify package lists
  ansible.builtin.assert:
    that:
      - arch_common_pkgs is defined
      - arch_graphical_pkgs is defined
    success_msg: "Arch package lists were defined"
    fail_msg: "Arch package lists were not defined"

- name: Configure the Pacman config file
  become: true
  community.general.ini_file:
    path: /etc/pacman.conf
    section: "{{ pacman_conf.section }}"
    option: "{{ pacman_conf.option }}"
    value: "{{ pacman_conf.value }}"
    create: true
    owner: root
    group: root
    mode: '0644'
  loop:
    - section: 'multilib'
      option: 'Include'
      value: '/etc/pacman.d/mirrorlist'
    - section: 'aur'
      option: 'SigLevel'
      value: 'Never'
    - section: 'aur'
      option: 'Server'
      value: 'file:///files/aur'
  loop_control:
    loop_var: pacman_conf

- name: Install common packages
  become: true
  community.general.pacman:
    name: "{{ arch_common_pkgs }}"
    state: present
    update_cache: true

- name: Install graphical packages
  become: true
  community.general.pacman:
    name: "{{ arch_graphical_pkgs }}"
    state: present
    update_cache: false
  when: ['graphics_enabled']
