# Install Arch Linux packages on top of initial install
---
- name: (PKG) Verify package lists
  ansible.builtin.assert:
    that:
      - arch_common_pkg is defined
      - arch_graphical_pkg is defined
    success_msg: "Arch package lists were defined"
    fail_msg: "Arch package lists were not defined"

- name: (PKG) Sync pacman.conf
  become: true
  ansible.builtin.copy:
    src: files/arch/pacman.conf
    dest: /etc/pacman.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: pacman-conf --config=%s

- name: (PKG) Install common packages
  become: true
  community.general.pacman:
    name: "{{ arch_common_pkg }}"
    state: present
    update_cache: true

- name: (PKG) Install graphical packages
  become: true
  community.general.pacman:
    name: "{{ arch_graphical_pkg }}"
    state: present
    update_cache: false
  when:
    - graphics_enabled
