# Install Arch Linux packages on top of initial install
---
- name: (Install Packages) Verify package lists
  ansible.builtin.assert:
    that:
      - debian_common_pkg is defined
    fail_msg: "Debian package lists were not defined"
  tags: packages

- name: (Install Packages) Install common packages
  become: yes
  ansible.builtin.apt:
    name: "{{ debian_common_pkg }}"
    state: present
    update_cache: yes
  tags: packages
