# Install Gentoo packages on top of initial install
---
# Ensure we have a list of packages to install defined
- name: Verify package lists were provided
  ansible.builtin.assert:
    that:
      - gentoo_common_pkg is defined
      - gentoo_graphical_pkg is defined
    success_msg: "Gentoo package lists were defined"
    fail_msg: "Gentoo package lists were not defined"

# Update our package cache before installing new packages
- name: Update package cache for Gentoo systems
  become: true
  portage:
    sync: true

# Install Gentoo packages on Gentoo systems
- name: Install common packages for Gentoo systems
  become: true
  portage:
    package: "{{ item }}"
    state: present
  loop: "{{ gentoo_common_pkg }}"

- name: Install graphical packages for Gentoo systems
  become: true
  portage:
    package: "{{ item }}"
    state: present
  loop: "{{ gentoo_graphical_pkg }}"
  when:
    - graphics_enabled
