# Run validation tasks, then import common tasks by tag
---
- name: (Check) Ensure required variables were provided
  ansible.builtin.assert:
    that:
      - user is defined
      - appcache is defined
    success_msg: "Required variables were not defined."
    fail_msg: "Required variables were not defined."
  tags: always

- name: (Check) Ensure username exists
  ansible.builtin.user:
    name: "{{ user }}"
    state: present
  register: user_info
  tags: user

- name: (PKG) Install packages on Arch Linux
  ansible.builtin.include_tasks:
    file: "install_{{ ansible_facts['os_family'] | lower }}_pkg.yaml"
    apply:
      tags:
        - pkg
  tags: pkg

- name: (FLATPAK) Install flatpak packages
  ansible.builtin.include_tasks:
    file: install_flatpaks.yaml
    apply:
      tags:
        - flatpak
  tags: flatpak

- name: (USER) Configure user environment
  ansible.builtin.include_tasks:
    file: configure_user.yaml
    apply:
      tags:
        - user
  tags: user

- name: (SSH) Configure SSH
  ansible.builtin.include_tasks:
    file: configure_ssh.yaml
    apply:
      tags:
        - ssh
  tags: ssh
