# Tasks for setting up automated backups of my fileserver
---
- name: (STORAGE) Create directory for backup-fileserver logs
  become: true
  ansible.builtin.file:
    path: /var/log/custom
    state: directory
    owner: root
    group: root
    mode: '0750'

- name: (STORAGE) Copy timer for backup-filserver.service
  become: true
  ansible.builtin.copy:
    src: backup-fileserver.timer
    dest: /etc/systemd/system/backup-fileserver.timer
    owner: root
    group: root
    mode: '0640'
  notify: Enable backup timer

- name: (STORAGE) Copy backup-fileserver.service
  become: true
  ansible.builtin.copy:
    src: backup-fileserver.service
    dest: /etc/systemd/system/backup-fileserver.service
    owner: root
    group: root
    mode: '0640'
