---
- name: (STORAGE) Create directory for backup-fileserver logs
  become: yes
  ansible.builtin.file:
    path: /var/log/custom
    state: directory
    mode: '0750'
  tags: storage

- name: (STORAGE) Copy timer for backup-filserver.service
  become: yes
  ansible.builtin.copy:
    src: backup-fileserver.timer
    dest: /etc/systemd/system/backup-fileserver.timer
    owner: root
    group: root
    mode: '0640'
  notify: Enable backup timer
  tags: storage

- name: (STORAGE) Copy backup-fileserver.service
  become: yes
  ansible.builtin.copy:
    src: backup-fileserver.service
    dest: /etc/systemd/system/backup-fileserver.service
    owner: root
    group: root
    mode: '0640'
  tags: storage

- name: (STORAGE) Enable backup-fileserver units
  become: yes
  ansible.builtin.service:
    name: "backup-fileserver.timer"
    enabled: true
    state: started
  tags: storage
