---
- name: (EXPORTS) Add /files to be exported
  become: true
  lineinfile:
    path: /etc/exports
    line: '/files    *(rw,sync,no_root_squash)'
    regexp: '^/files\s'
    state: present

- name: (EXPORTS) Enable and start NFS server service
  become: true
  systemd:
    name: nfs-server
    state: started
    enabled: true
