# Setup my Direct-Attached Storage (DAS) solution
---
- name: (STORAGE) Create mountpoint directories
  become: true
  ansible.builtin.file:
    path: "{{ mountpoint }}"
    state: directory
    mode: '0755'  
  loop:
    - '/backup'
  loop_control:
    loop_var: mountpoint
  tags: storage
- name: (STORAGE) Mount primary drives
  become: true
  ansible.posix.mount:
    path: "{{ mount.path }}"
    src: "{{ mount.src }}"
    fstype: "{{ mount.fs }}"
    opts: rw
    state: mounted
  loop:
    - {src: 'LABEL=files', path: '/files', fs: 'btrfs'}
    - {src: 'LABEL=backupfiles', path: '/backup/files', fs: 'xfs'}
  loop_control:
    loop_var: mount
  tags: storage
