# Playbook for configuration after a fresh install
---
- hosts: "{{ target_hosts }}"
  gather_facts: true
  vars_prompt:
    - name: target_hosts
      prompt: "Target Hosts"
      private: false
  tasks:
    - ansible.builtin.include_role:
        name: common
      tags: ['always']
    - ansible.builtin.include_role:
        name: storage
      tags: ['storage', 'exports']
    - ansible.builtin.include_role:
        name: hypervisor
      tags: ['hypervisor']
